name: API Deployment

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build API
    steps:
      - uses: actions/checkout@v4

      - name: Set up maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
      
      - name: Build with maven
        run: mvn clean install

      - name: Rename files
        run: mv target/app-1.war target/app.war 

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: "target/app.war"
          name: artifcat-${{ github.run_id }}