name: API Deployment

on: 
  workflow_dispatch

run-name: "Deployment for branch: ${{ github.ref_name }} with commit: ${{ github.sha }}"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build API & Image
    steps:
      - uses: actions/checkout@v4

      - name: Set up maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
      
      - name: Build with maven
        run: mvn clean install

      - name: Rename files
        run: mv target/app-1.war target/app.war 

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Docker build & push
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: .
          tags: tanmayrao7/test-tomcat-app:${{ github.sha }}
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          push: true
    
  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: dev
      url: https://dev.application.com

    steps:
      - name: Image tag update
        run: |
          chmod +x image_tag_updater.sh
          sh image_tag_updater.sh DEV
      - name: argocd app sync
        run: |
          chmod +x argocd_sync_apps.sh
          sh argocd_sync_apps.sh DEV

  deploy-to-qa:
    runs-on: ubuntu-latest
    needs: [build]

    environment:
      name: qa
      url: https:/qa.application.com

    steps:
      - name: Image tag update
        run: |
          chmod +x image_tag_updater.sh
          sh image_tag_updater.sh QA
      - name: argocd app sync
        run: |
          chmod +x argocd_sync_apps.sh
          sh argocd_sync_apps.sh QA

  deploy-to-prod:
    runs-on: ubuntu-latest
    needs: [build]

    environment:
      name: prod
      url: https:/prod.application.com

    steps:
      - name: Image tag update
        run: |
          chmod +x image_tag_updater.sh
          sh image_tag_updater.sh PROD
      - name: argocd app sync
        run: |
          chmod +x argocd_sync_apps.sh
          sh argocd_sync_apps.sh PROD
